server:
  port: ${PORT:8001}

spring:
  application:
    name: customer-service

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}

---
spring:
  profiles: heroku
  application:
    instance_id: ${DOMAIN_NAME}
    instanceId: ${DOMAIN_NAME}
  # cloud:
  #   client:
  #     hostname: ${HOSTNAME}
eureka:
  instance:
    # instanceId: ${spring.application.name}:${DOMAIN_NAME:${spring.application.instance_id:${random.value}}}
    nonSecurePort: 80