server:
  port: ${PORT:8761}
  
eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
  client:
    registerWithEureka: false
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}
